name: CI
on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mirroring Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          cygwin@cygwin.com:/git/cygwin-packages/opam
        ssh_private_key:
          ${{ secrets.CYGWIN_SSH_PRIVATE_KEY }}
